version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: sprinkler-backend
    expose:
      - "8000"
    environment:
      - uid=${UID:-1000}
      - gid=${GID:-1000}
      - gid_gpio=${GID_GPIO:-1000}
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - TZ=Europe/Prague
    volumes:
      # Map the firmware config files so they persist between container restarts
      - ./firmware/src/valves.json:/app/firmware/src/valves.json
      - ./firmware/src/schedules.json:/app/firmware/src/schedules.json
      
      # udev rules for GPIO
      - /etc/udev/rules.d:/etc/udev/rules.d
      # system access for GPIO
      - /dev:/dev
      - /sys:/sys
      - /proc:/proc
      - /sys/class/gpio:/sys/class/gpio
      - /sys/devices:/sys/devices
    devices:
      - /dev/gpiochip0:/dev/gpiochip0 # for GPIO
      - /dev/gpiochip1:/dev/gpiochip1 # for GPIO
    privileged: true
    networks:
      - sprinkler-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sprinkler-frontend
    expose:
      - "5173"
    depends_on:
      - backend
    networks:
      - sprinkler-network

  nginx:
    image: nginx:alpine
    container_name: sprinkler-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - sprinkler-network

networks:
  sprinkler-network:
    driver: bridge
