version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "200k"
    max-file: "5"

services:
  # jetson-sprinkler:
  #   image: test
  #   container_name: jetson-sprinkler
  #   restart: always
  #   environment:
  #     uid: $UID
  #     gid: $GID
  #     gid_gpio: $GID_GPIO
  #   volumes:
  #     # udev rules for GPIO
  #     - /etc/udev/rules.d:/etc/udev/rules.d
  #     # system access for GPIO
  #     - /dev:/dev
  #     - /sys:/sys
  #     - /proc:/proc
  #     - /sys/class/gpio:/sys/class/gpio
  #     - /sys/devices:/sys/devices
  #   devices:
  #     - /dev/gpiochip0:/dev/gpiochip0 # for GPIO
  #     - /dev/gpiochip1:/dev/gpiochip1 # for GPIO
  #   user: $UID:$GID
  #   privileged: true
  #   depends_on: 
  #     - mongo-db
  #   logging: *default-logging
  #   entrypoint: /bin/bash

  # ui:

  # server:

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=sprinkler
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=Mongo1
    volumes:
      - ./mongodb_init.js:/docker-entrypoint-initdb.d/mongodb_init.js:ro
    logging: *default-logging

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: Mongo1
    logging: *default-logging 
    depends_on: 
      - mongo     
