version: '3'

services:
  jetson-sprinkler:
    image: test
    container_name: jetson-sprinkler
    environment:
      uid: $UID
      gid: $GID
      gid_gpio: $GID_GPIO
    entrypoint: /bin/bash
    volumes:
      # udev rules for GPIO
      - /etc/udev/rules.d:/etc/udev/rules.d
      # system access for GPIO
      - /dev:/dev
      - /sys:/sys
      - /proc:/proc
      - /sys/class/gpio:/sys/class/gpio
      - /sys/devices:/sys/devices
    devices:
      - /dev/gpiochip0:/dev/gpiochip0 # for GPIO
      - /dev/gpiochip1:/dev/gpiochip1 # for GPIO
    user: $UID:$GID
    privileged: true
